// Simple runtime dev check for icon hydration mismatches
// This file is only used in development to catch potential issues

export function checkIconHydration() {
  if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
    // These are the *expected* classes generated by Lucide React for these specific icons
    const expectedClasses = [
      'lucide-building2',    // For Icon name="building2"
      'lucide-globe2',      // For Icon name="globe2"
      'lucide-bar-chart-3', // For Icon name="bar-chart-3"
      'lucide-chevron-down',
      'lucide-rocket',
      'lucide-trending-up',
      'lucide-star',
      'lucide-bot',
      'lucide-server-cog',
      'lucide-panels-top-left',
      'lucide-key-round',
    ];

    // These are *unexpected* classes that would indicate a mismatch
    const unexpectedClasses = [
      'lucide-building-2', // If Lucide generates building2, then building-2 is wrong
      'lucide-globe-2',    // If Lucide generates globe2, then globe-2 is wrong
      // No specific "barchart3" vs "bar-chart-3" issue, as bar-chart-3 is hyphenated
    ];

    expectedClasses.forEach(expectedClass => {
      const elements = document.querySelectorAll(`svg[class*="${expectedClass}"]`);
      if (elements.length > 0) {
        console.log(`✅ Found ${elements.length} SVG(s) with expected class "${expectedClass}"`);
      } else {
        console.warn(`⚠️ Did not find any SVG(s) with expected class "${expectedClass}"`);
      }
    });

    unexpectedClasses.forEach(unexpectedClass => {
      const elements = document.querySelectorAll(`svg[class*="${unexpectedClass}"]`);
      if (elements.length > 0) {
        console.error(
          `❌ Found ${elements.length} SVG(s) with UNEXPECTED class "${unexpectedClass}". ` +
          `This indicates a hydration mismatch. Please check Icon.tsx MAP and icon usages.`
        );
      }
    });
  }
}

// Auto-run in development
if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  // Run after a short delay to ensure DOM is ready
  setTimeout(checkIconHydration, 100);
}
